api.http.host: 0.0.0.0
api.http.port: 9600
config.reload.automatic: true
config.reload.interval: 3s
log.format: plain
log.level: info
monitoring.enabled: false
node.name: bms-logstash
path.config: /usr/share/logstash/pipeline
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs
pipeline.batch.delay: 50
pipeline.batch.size: 1000
pipeline.unsafe_shutdown: false
slowlog.threshold.debug: 1s
slowlog.threshold.info: 2s
slowlog.threshold.trace: 500ms
slowlog.threshold.warn: 5s
xpack.monitoring.enabled: false
